### PR TITLE
Bug fix preventing Pkg Deps tab from crashing when dep info not available

### LINKED ISSUE #802: Package Deps tab crashes for some pkgs
Currently effecting `dev`, `master`, and our two demo branches: Found that `gower` and `corrplot` will take down the app. Here is the console output:

```
Warning: Detailed dependency information is not available for package gower
Warning: info: Error in `mutate()`:
ℹ In argument: `package = stringr::str_replace(package, "\n", " ")`.
Caused by error:
! object 'package' not found

Warning: Error in mutate: ℹ In argument: `dec_cat = factor(...)`.
Caused by error:
! object 'decision' not found
  102: <Anonymous>
  101: signalCondition
  100: signal_abort
   99: abort
   98: h
   97: .handleSimpleError
   96: is_logical
   95: check_logical
   94: if_else
   93: factor
   92: eval
   91: mask$eval_all_mutate
   90: mutate_col
   89: withCallingHandlers
   88: mutate_cols
   87: mutate.data.frame
   86: mutate
   85: mutate
   84: group_by
   83: summarize
   82: ungroup
   81: mutate
   80: mutate
   79: arrange
   78: %>%
   77: build_dep_cards [C:/Users/aclark02/Documents/Projects/Github2/riskassessment/R/utils_build_cards.R#352]
   76: force [C:/Users/aclark02/Documents/Projects/Github2/riskassessment/R/mod_packageDependencies.R#132]
   75: cards
   74: observe [C:/Users/aclark02/Documents/Projects/Github2/riskassessment/R/mod_packageDependencies.R#132]
   73: <observer>
   72: valueFunc
   71: ..stacktraceon..
   70: contextFunc
   69: env$runWith
   68: force
   67: domain$wrapSync
   66: promises::with_promise_domain
   65: withReactiveDomain
   64: domain$wrapSync
   63: promises::with_promise_domain
   62: ctx$run
   61: ..stacktraceoff..
   60: isolate
   59: func
   58: withVisible
   57: f
   56: Reduce
   55: withCallingHandlers
   54: domain$wrapSync
   53: promises::with_promise_domain
   52: captureStackTraces
   51: doTryCatch
   50: tryCatchOne
   49: tryCatchList
   48: tryCatch
   47: do
   46: hybrid_chain
   45: observeEvent(list(pkgref(), toggled()))
   44: contextFunc
   43: env$runWith
   42: force
   41: domain$wrapSync
   40: promises::with_promise_domain
   39: withReactiveDomain
   38: domain$wrapSync
   37: promises::with_promise_domain
   36: ctx$run
   35: run
   34: withCallingHandlers
   33: domain$wrapSync
   32: promises::with_promise_domain
   31: captureStackTraces
   30: withCallingHandlers
   29: shinyCallingHandlers
   28: force
   27: withVisible
   26: withCallingHandlers
   25: domain$wrapSync
   24: promises::with_promise_domain
   23: captureStackTraces
   22: doTryCatch
   21: tryCatchOne
   20: tryCatchList
   19: tryCatch
   18: do
   17: hybrid_chain
   16: flushCallback
   15: FUN
   14: lapply
   13: ctx$executeFlushCallbacks
   12: .getReactiveEnvironment()$flush
   11: flushReact
   10: serviceApp
    9: ..stacktracefloor..
    8: withCallingHandlers
    7: domain$wrapSync
    6: promises::with_promise_domain
    5: captureStackTraces
    4: ..stacktraceoff..
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Detailed dependency information is not available for package gower
Warning in datatable_custom(data_table(), custom_dom = "lftpi") :
  number of provided colnames unequal to number of columns in data. 
            Defaulting to original data frame names.
```

### PR DESCRIPTION
**Pull request by aclark02-arcus**
Closes #802

### CODE REVIEW

**Comment by jthompson-arcus** [comment]
So this PR has me thinking more about what is actually going on in these lines of code. The problem is that an empty dependency table or suggests table does not mean the information is not available, but our code outputs a warning in that case. I think we should only be triggering this warning if `riskmetric` is returning an error for the dependencies metric.

File: R/mod_packageDependencies.R [hunk 1]
```diff
@@ -123,7 +124,13 @@ packageDependenciesServer <- function(id, selected_pkg, user, credentials, paren
         }
       )
       # this is so the dependencies is also a 0x2 tibble like suggests
-      if (rlang::is_empty(pkgref()$dependencies[[1]])) depends(dplyr::tibble(package = character(0), type = character(0), name = character(0)))
+      if (rlang::is_empty(pkgref()$dependencies[[1]])) {
```
Comment (jthompson-arcus) [inline R/mod_packageDependencies.R:127]: Meant to comment on this earlier, but these lines seem completely unnecessary base on the `tryCatch()`'s above

Comment (aclark02-arcus) [reply R/mod_packageDependencies.R:127]: Ironically, this change is what actually prevents the app from crashing. But you're right. It is redundant since the tryCatch handles it. I removed it with a recent commit.

**Review by jthompson-arcus — APPROVED** [review]
